### ISSUE TITLE
Allow bots to work in custom workshop maps

### ISSUE THREAD

**Issue by dtracers** [RLBot/RLBot#105]

**Comment by ddthj** [comment]
Stale.
Workaround exists though:

1: Find the workshop map you want to use. It will be located at C:\Program Files (x86)\Steam\steamapps\workshop\content\252950, Find the map you want inside one of those folders.
The map has a .udk extension.
2: Change the map name to Labs_Underpass_P.upk. Be sure to change the extension as well.
3: Copy the map to C:\Program Files (x86)\Steam\steamapps\common\rocketleague\TAGame\CookedPCConsole. It will replace the Underpass map.
4: On RLBotGui select Underpass to play the custom map.
