### ISSUE TITLE
Check for locked files before attempting pip upgrade of rlbot

### ISSUE THREAD

**Issue by tarehart** [RLBot/RLBot#130]
If somebody has rocket league open and the dll injected, upgrading the rlbot python package will fail because the dll is locked. It would probably also fail if the interface dll was in use.

The batch files which attempt to upgrade rlbot should check first to see if the files are locked, and if so, skip the update. There are multiple examples of such batch files, one is here: https://github.com/RLBot/RLBotPythonExample/blob/master/run.bat#L5

Possible way to check for locked files: https://www.dostips.com/forum/viewtopic.php?t=5542

To locate the rlbot install location, consider using get_python_root() from here: https://github.com/RLBot/RLBot/blob/v4/src/main/python/rlbot/utils/class_importer.py#L86

**Comment by Sciguymjm** [comment]
Or, check if Rocket League is running.

**Comment by tarehart** [comment]
I suspect that upgrade would also fail if a process were using the interface dll, which can happen even if Rocket League is not running. I'd rather err on the side of caution and check the whole rlbot folder.
