### ISSUE TITLE
Java Bot duplication

### ISSUE THREAD

**Issue by nevercast** [RLBot/RLBot#149]
Java bots can sometimes become duplicated when rejoining the runner. https://github.com/RLBot/RLBot/pull/148 should have fixed this.

This issue is to ensure #148 worked.

**Comment by nevercast** [comment]
I've not seen this issue for a very long time, how about you @tarehart ? I'm a trigger finger away from closing as Resolved.

**Comment by tarehart** [comment]
Neither have I! I'll go ahead and resolve.

**Comment by tarehart** [comment]
Aaand it happened to somebody today

**Comment by nevercast** [comment]
Did they manage to give us any information?

**Comment by ddthj** [comment]
Stale, I ain't seen no clonin' java bots in a loooong time.
