### ISSUE TITLE
Quickest way to play against the best bots?

### ISSUE THREAD

**Issue by AdityaAnand1** [RLBot/RLBot#177]
I'm here after checking out the trailer for the upcoming bot tournament.

I gave RLbot a shot last year and back then I remember there weren't a lot of human level bots, now I'm seeing aerials in the trailers.

First of all, fantastic work! Second of all, how do I play against some of these amazing bots?

**Comment by tarehart** [comment]
Thanks! If you join the discord, I can help you get set up with RashBot - https://discord.gg/zbaAKPt

There will be more to choose from after the tournament.

**Comment by AdityaAnand1** [comment]
@tarehart Thank you!

Although, isn't there some kind of setup documentation? I can join discord, sure, but I have a feeling plenty of others will be coming around here soon. I'm not sure why there's so much apparent secrecy around this 😅 

I just want a nicer bot to play against but I can't seem to find anything on setting up 2017 tournament bots either.

**Comment by dtracers** [comment]
There is no secrecy but github issues is not the best way to tell people how to setup, it is for bugs and feature requests.

If you look at the readme of this repo there is in fact setup documentation.
And if you look on discord there are even more setup documentation.

2017 tournament bots use an old version of the framework and do not work with rocket league anymore

**Comment by AdityaAnand1** [comment]
I completely understand but my point is, wouldn't it be better to make universal setup instructions once rather than helping one guy (like me) figure it out one at a time. I just don't want to waste anyone's time :)

Indeed I did follow the instructions in this repo, but it's only like some kind of boilerplate starter bot (I'm guessing) that didn't do much. Where is the code for the latest better skilled bots? Are there no binaries available? If there were, the custom bot scene would blow up. I'd love to contribute myself (say, in making one-click installs so people like me don't annoy you) but I need to figure it out for myself once first and the current documentation hasn't gotten me all the way there.

I'll go and join discord.
