### ISSUE TITLE
Crash after BOTNAMEHERE(appearance).cfg

### ISSUE THREAD

**Issue by Mryourface13** [RLBot/RLBot#192]
Crashes after appearance.cfg instead of at CONFIGNAME.cfg caused by mistyping a filepath in the RLBot GUI/nongui loader.

**Comment by ddthj** [comment]
I nuked my config file and the RLBotGUI handled it pretty gracefully, launched a match and used a default appearance. Since the RLBotGUI deals with paths automagically now there's not an opportunity to mistype a path to your bot.
