### ISSUE TITLE
Requirements.txt

### ISSUE THREAD

**Issue by SakiiR** [RLBot/RLBot#20]
Adding a requirements.txt would be great :)

**Comment by tarehart** [comment]
We could add a link to https://github.com/drssoccer55/RLBot/wiki/Setup-Instructions inside README.md, would that get the job done?

**Comment by drssoccer55** [comment]
Oh whoops I never added the discord link to the README.md either.  I think linking existing resources is better than adding another file.  Requirements are already loosely described in the README.md.

**Comment by DomNomNom** [comment]
Looks like @tarehart addressed this in [this recent commit](https://github.com/RLBot/RLBot/commit/c3716303244c24ffda1e2b40f9a22e4062a36f80#diff-b4ef698db8ca845e5845c4618278f29a)

**Comment by SakiiR** [comment]
It's a requirement to have a requirements.txt in your python package directory ;)

**Comment by tarehart** [comment]
By the way, I had no idea that `requirements.txt` had special meaning in the python world when this issue was first opened :)

**Comment by SakiiR** [comment]
No problem, it's up to you, generally better to have one
