### ISSUE TITLE
Bot sending wrong Quick-Chat messages

### ISSUE THREAD

**Issue by atalantus** [RLBot/RLBot#217]
Since the [RLBot Framework version 0.0.28](https://github.com/RLBot/RLBot/pull/202) the quick-chat messages seems to have some weird offset leading to the bot sending the wrong messages.

Results with python bot and message visibility `CHAT_EVERYONE` using the QuickChatSelection [here](https://github.com/RLBot/RLBot/blob/master/src/main/flatbuffers/rlbot.fbs):

    expected Id in code -> actual message id

    0 -> 36
    1 -> 37
    10 -> 8
    20 -> 48
    21 -> 50
    33 -> 4
    34 -> 2
    55 -> 19
    57 -> 16

**Comment by TheBlocks** [comment]
Do you still get this bug with RLBot 0.0.29?

**Comment by atalantus** [comment]
Yes. My code worked up to `0.0.26`

Simple (agent is my `BaseAgent` object):

    self.agent.send_quick_chat(QuickChats.CHAT_EVERYONE, QuickChats.Reactions_Siiiick)

**Comment by atalantus** [comment]
Fixed with https://github.com/RLBot/RLBot/pull/221
