### ISSUE TITLE
Keep RLBot out of ranked, but allow RLBot to work in LAN and private matches.

### ISSUE THREAD

**Issue by girtonman** [RLBot/RLBot#22]
Would be great for scrimming without needing to share code.

**Comment by dtracers** [comment]
LAN, private, online all follow the same code path so it will be near impossible to block 2 while keeping the one.

**Comment by TheWaffleDimension** [comment]
Analyze the packets?

**Comment by martmists** [comment]
This will be addressed when the official Bot API releases.

**Comment by TheBlocks** [comment]
Closing issue because this will be available after the new API from Psyonix is adopted.

**Comment by dtracers** [comment]
We will leave this open until we have documentation about how to use LAN with RLBot

**Comment by TheBlocks** [comment]
Closing issue because this is available from the Psyonix API and has been implemented. See https://github.com/RLBot/RLBot/wiki/LAN-Setup.
