### ISSUE TITLE
Sometimes rendering doesn't work. Nothing is drawn and it prints 'bad status BufferOverfilled'

### ISSUE THREAD

**Issue by NicEastvillage** [RLBot/RLBot#233]
Nothing is drawn and it keeps printing 'bad status BufferOverfilled', even though it is just supposed to draw a single line. Pressing page up/down doesn't change anything. Restarting Rocket League resolves it.

@ TDG experienced it during the SpeedBot challange tournament.

**Comment by NicEastvillage** [comment]
I don't know if this is still a bug

**Comment by IamEld3st** [comment]
I don't know if thios was noted... but there is also a possibility that rendering shouts BufferOverfilled but the rendering still works.

**Comment by ddthj** [comment]
Unless you actually overfill the buffer you shouldn't get BufferOverfilled anymore. Source: me
Also this issue is stale.
