### ISSUE TITLE
Main thread crashes when reading game packet on second match

### ISSUE THREAD

**Issue by dtracers** [RLBot/RLBot#252]
When trying to read the game tick packet on the second match the thread crashes with an illegal access.

No stack trace is created.
This is near 100% reproduceable but it does not happen every time. 
This is blocking features for automating matches.

**Comment by tarehart** [comment]
Can be replicated by running a second match via https://github.com/RLBot/RLBot/tree/extensinos according to dtracers

**Comment by Dadle** [comment]
Can also be replicated by isntalling and running this [repo](https://github.com/CapgeminiNorway/RocketLeagueAIBackEnd): https://github.com/CapgeminiNorway/RocketLeagueAIBackEnd

**Comment by TheBlocks** [comment]
No longer an issue.
