### ISSUE TITLE
Add support for rendering from a list of lines

### ISSUE THREAD

**Issue by TheBlocks** [RLBot/RLBot#253]
There should be a way to give the renderer a list of points which would be drawn connected together.

**Comment by tarehart** [comment]
It could be a helper method defined here: https://github.com/RLBot/RLBot/blob/master/src/main/python/rlbot/utils/rendering/rendering_manager.py

Please note that the renderer only supports drawing a certain amount of data in a single call. If the user passes a super long list, you have to decide whether to give them an error or try to break it into multiple calls on their behalf.

**Comment by tarehart** [comment]
Functionality added by #254
