### ISSUE TITLE
Readme: broken link

### ISSUE THREAD

**Issue by chardetm** [RLBot/RLBot#275]
"@Tarehart's ball path prediction DLL based on @Chip's work (Work in progress)" is a broken link in the readme (error 404, or maybe the project is private)

**Comment by skyborgff** [comment]
deleted, it is no longer in progress, it is in the framework

**Comment by tarehart** [comment]
You can find an explanation of how to use it at https://github.com/RLBot/RLBot/wiki/Ball-Path-Prediction !
