### ISSUE TITLE
Porting to linux

### ISSUE THREAD

**Issue by Ridhwanluthra** [RLBot/RLBot#277]
Since rocket league is available for linux, most AI developers use linux and this package is gaining a lot of traction.
It only makes sense to port it to linux (I am willing to help with this)

The reason I am interested is that I want to develop some bots using machine learning and my environment is set up in linux.
What all needs to be changed and ported for using this with linux.

**Comment by skyborgff** [comment]
We currently use dll injection on windows. i dont know how would one go about to make the equivalent in linux, but that is the only part that we need in order to work in linux.

**Comment by samuelpmish** [comment]
There is an active community in RLBot that does machine learning for Rocket League on Windows. Most ML tools I'm aware of are cross platform, have you looked into getting your own environment working on Windows instead?

**Comment by Ridhwanluthra** [comment]
@skyborgff I did find out about some tools that help with .so injection similar to dll injection. Since I have no experience with this before if you know someone who can guide me a little I could try to work on it.

@samuelpmish Ya that's what I am doing for now, but I hate windows, its just horrible. So was willing to put the efforts in porting to linux

**Comment by skyborgff** [comment]
@Ridhwanluthra i have no idea how this would work on linux.
There have been some people over at discord that have shown interest in helping with a port, for example @Entrybot#2128 and @ClassicRushy#4977 
Come, tag them, and you can discuss how to do it

**Comment by martmists** [comment]
> We currently use dll injection on windows. i dont know how would one go about to make the equivalent in linux, but that is the only part that we need in order to work in linux.

As discussed in the discord earlier today, this can be achieved by either owning the rocket league process with a `fork()` call, or setting a kernel value with `echo 0 | sudo tee /proc/sys/kernel/yama/ptrace_scope`, both easy to do, and then injection can be achieved with `ptrace`. 

To simplify matters, there is a project called [gaffe23/linux-inject](https://github.com/gaffe23/linux-inject) which does just this.

**Comment by IamEld3st** [comment]
@martmists there is no need to overcomplicate as rlbot can be injected at game start therefore using just LD_PRELOAD is just fine... only roadblocks i can think of is 32bit->64bit and some stuff that uses windows libs to function... again none of them might cause problems... also some runner and framework functions depends on windows libs so thats another thing that needs to get ported

**Comment by martmists** [comment]
the `msvcrt` library can be replaced with `sys.stdin.read(1)` in a thread or using prompt_toolkit, and most `windows.h` functions can be replaced with glibc functions, not sure which ones would be missing though.

**Comment by DomNomNom** [comment]
This hopefully becomes easy once the official API is released.
https://docs.google.com/document/d/1K5HhRm5CBguYleISqQjxT1GY_H2W9msWrIo3DGAblwE/edit

**Comment by Qinusty** [comment]
Is there any updates on this?

**Comment by IamEld3st** [comment]
@Qinusty RLBot now works on linux... not all languages but it runs... last time i checked python and rust were working or atleast very close to.

**Comment by Quetzal2** [comment]
I am using it right now! :) Works well. I haven't had any Linux build specific issue yet.

**Comment by martmists** [comment]
Has anyone been able to test Lua?

**Comment by DomNomNom** [comment]
Closing this issue as [Linux support has been implemented in RLBot](https://github.com/RLBot/RLBot/wiki/Operating-System-Support). :tada: 
Big thanks to Kipje13, Psyonix, and everyone else that helped for making this happen.

If there are any bugs with RLBot on Linux, please create new issues.
