### ISSUE TITLE
Example bots refuse to run if there's no internet connection

### ISSUE THREAD

**Issue by tarehart** [RLBot/RLBot#288]
When running an example bot, e.g. RLBotPythonExample, the script will first try to upgrade rlbot. This requires an internet connection, and currently it appears to retry forever. Instead, it should give up and proceed with the current version of rlbot.

I believe this problem was introduced when I switched to the run.py script.

**Comment by ima9rd** [comment]
Addressed with pull request 9 on the RLBotPythonExample repo.

**Comment by ima9rd** [comment]
I believe this was addressed with the have_internet and Python example PRs. Are there any lingering issues related to this?

**Comment by TheBlocks** [comment]
Fixed with https://github.com/RLBot/RLBotPythonExample/pull/9.
