### ISSUE TITLE
Add Gravity-related features.

### ISSUE THREAD

**Issue by RLMarvin** [RLBot/RLBot#306]
Add a way to **get** and **set** gravity and use it as a parameter for ball prediction.

**Comment by nevercast** [comment]
I spoke to Bakkes about this a few weeks ago.

>Use `WorldInfo->WorldGravityZ`
> But make sure it isn't exactly 0, but 0.00001
> If 0 then it will set it to default

**Comment by skyborgff** [comment]
Nevercast, there was 0 need to ask bakkes, I personally have played around with that value and found the same behaviour with 0. 
This would require a better documentation for the state setting as we have been holding on to the idea that it was the same structure as the game packet, so no documents on what it supports was needed (this is kinda an excuse 😋). But this could also be added to the game tick packet.

**Comment by nevercast** [comment]
Well Sky, I don't have access to the core source. So I acted of my own capability. :)

**Comment by skyborgff** [comment]
Ahh ok, i thought you had been researching for rlbot, on which case, asking should have been the first option :P
I'm not fluent enough with c++ to be capable of adding it myself though if it is indeed to be added

**Comment by hallo-doei** [comment]
Has been addressed in PR #315 and is ready to be pushed to pip with the next update!
