### ISSUE TITLE
Can't start match while in unfair game.

### ISSUE THREAD

**Issue by RLMarvin** [RLBot/RLBot#314]
This happens when we're in a normal unfair exhibition match, after running rlbot the game gets stuck in the loading screen.

A debug core dll repeatedly prints out the following : 
```
Team configuration does not match!
To determine whether we're in training, checking if GameEvent_Soccar_TA IsA GameEvent_Tutorial_TA or GameEvent_TrainingEditor_TA
```

**Comment by ddthj** [comment]
Can't reproduce. Time heals all wounds.
