### ISSUE TITLE
Incorrect timing between get_output calls in python

### ISSUE THREAD

**Issue by kipje13** [RLBot/RLBot#358]
When running a python bot with the fps set to 120, the time between two get_output calls is approximatly 10ms as can be seen here:

![](https://cdn.discordapp.com/attachments/348659150793736193/535428760888147968/unknown.png)

At 120fps we should be expecting a time of about 8ms. Since we are considerably over that limit, we are dropping about 1 in 5/6 frames.

When running a python bot at 60 fps, the time between get_output calls is approximatly 20ms. We should be expecting 16ms in this case.

![](https://cdn.discordapp.com/attachments/348659150793736193/535431891487162378/unknown.png)

As can be seen here, we run 2/3 frames at 20ms, followed by a 10ms frame. This Presumably happens to catch up from the time lost on the previous frames. 

This will limit the effective time budget to 10ms. When going over 10ms, you will drop about 1 in 3/4 frames.

**Comment by ddthj** [comment]
This is stale, and has a much cooler variant over here: #445
