### ISSUE TITLE
Freeze after restarting match after it has concluded

### ISSUE THREAD

**Issue by DomNomNom** [RLBot/RLBot#360]
Steps to reproduce:
- Start a match with RLBot (I used the GUI) e.g. 1v1 NomBot vs NomBot
- Wait for it to complete
- click "ready" at the final score screen
- We should now be in a state where we a human is facing a psyonix bot.
- Click on "start match" in the RLBotGUI.
- Game goes into loading state

Observed behaviour:
 - Game gets stuck on loading screen
 - RocketLeague.exe consumes 4 cores of CPU and freezes for 1 second every 2 seconds.
 - After exiting the RLBotGUI and closing the Rocket League window, RocketLeague.exe is still running and needs to get killed via taskmanager!

Expected behaviour:
 - Game loads the match.

https://github.com/RLBot/RLBot/issues/314 is possibly related.

**Comment by DarinDev1000** [comment]
I have the same issue!

**Comment by DomNomNom** [comment]
Possibly symptoms and a quicker way to reproduce this: Start a match with 2 bots, then start a match with one bot. Then observe that `game_tick_packet.num_cars == 2` is still the case

**Comment by ddthj** [comment]
The old workaround was to leave the human v AI match before starting a new RLBot match, but this bug no longer exists anyways.
