### ISSUE TITLE
Intermittent physics tick problems starting with 1.11.0

### ISSUE THREAD

**Issue by tarehart** [RLBot/RLBot#362]
From @whatisaphone 

>The latest dll doesn't update the physics ticks consistently anymore
I can reliably fix it by downgrading to 1.10.0, and break it again at 1.11.0

>the render tick is fine

>it's happened on 2/4 systems (so far). chip also didn't see it

Also seemed evident on jeroen's stream.

**Comment by tarehart** [comment]
I haven't been able to dupe yet, but based on the version numbers, this is probably related to https://github.com/skyborgff/rlbot-core/pull/43 or https://github.com/skyborgff/rlbot-core/pull/44

**Comment by whatisaphone** [comment]
Yes good call I should have filed an issue, thanks for doing it for me. The issue in video form:

![](https://cdn.discordapp.com/attachments/348659150793736193/536563779740106762/sad_physics_ticks.gif)

I just bisected among the commits listed at https://github.com/RLBot/RLBot/commits/master/src/main/python/rlbot/dll

<details>
<summary>(using this handy script that I'll put here for safekeeping)</summary>
ref=0ed61d1; for url in https://github.com/RLBot/RLBot/raw/"$ref"/src/main/python/rlbot/dll/BallPrediction.exe https://github.com/RLBot/RLBot/raw/"$ref"/src/main/python/rlbot/dll/RLBot_Core.dll https://github.com/RLBot/RLBot/raw/"$ref"/src/main/python/rlbot/dll/RLBot_Core_Interface.dll https://github.com/RLBot/RLBot/raw/"$ref"/src/main/python/rlbot/dll/RLBot_Core_Interface_32.dll https://github.com/RLBot/RLBot/raw/"$ref"/src/main/python/rlbot/dll/RLBot_Injector.exe; do ( cd /c/Path && curl -OL "$url" ); done
</details><br>

The last good commit is: 0ed61d1
The first bad commit is: 4f9291b

I will dig further when I have time

**Comment by tarehart** [comment]
Thanks for doing the bisect, that helps! That commit corresponds to https://github.com/skyborgff/rlbot-core/pull/44

I'll try again to dupe. Next step is probably to dupe with a debug dll and see if there are errors in the console.

Did you say there was anything unusual with CPU utilization related to this? I vaguely remember that but can't find the comment.

**Comment by whatisaphone** [comment]
I found the issue! See #364
