### ISSUE TITLE
Detecting ABI compatibility

### ISSUE THREAD

**Issue by whatisaphone** [RLBot/RLBot#364]
Looks like #362 was caused by an ABI incompatibility. (I can't explain the bizarre symptom, but updating the bindings fixed it for me.)

This has been a recurring issue, so we need a long-term fix. Previously we decided not to aim for backwards compatibility, and that's fine, but I think we should target the next-best thing—failing fast when things aren't compatible.

I had a couple ideas, but I think the best balance would be to annotate struts with their size. Every "root" struct (those that appear in an exported function signature, or what you'd call a `root_type` in flatbuffers) will have `size_t Size` as the first field (bikeshedding welcome):

```c
struct LiveDataPacket
{
    size_t                  Size;
	PlayerInfo 				GameCars[CONST_MaxPlayers];
	// …
```

* Structs passed **into** the interface will need to set this field to `sizeof(the_struct)`. The interface will verify that `theStruct->Size == sizeof(theStruct)`, and if not, return something like `RLBotError::IncompatibleVersion` (bikeshed away).
* Structs coming **from** the interface will be returned with the field set, and the caller rfc-2119-SHOULD check that the size matches what's expected.

Our changes to the structs have usually changed their size, and usually for the larger, so this will catch 99% of cases, and we can do it without introducing ABI versioning or any sort of ongoing bookkeeping.

Thoughts?

**Comment by DomNomNom** [comment]
Sounds like a step in the right direction :+1: 
Can we unit-test this?

**Comment by whatisaphone** [comment]
You mean like this? (pseudo-code)

```
void testVersioning() {
    DesiredGameState state;
    state.Size = 1;
    auto result = SetGameState(&state);
    assert(result == RLBotError::IncompatibleVersion);
}
```

**Comment by whatisaphone** [comment]
Tare and I talked on Discord and we're going with an alternate plan. We will declare that the struct methods are Python-only. RLBot will grow a flatbuffer version of the last remaining API that doesn't have one (StartMatch), and Rust will deprecate the non-flatbuffer APIs. Flatbuffers are backwards/forwards compatible, so this kind of thing won't be an issue anymore.
