### ISSUE TITLE
Add GUI option to speed up game

### ISSUE THREAD

**Issue by J-Wass** [RLBot/RLBot#379]
Great for users trying to build ML bots that need a large amount of training. Options to speed the game up to 3x would probably be most appropriate. Additionally, since training the bot for long hours might be resource intensive, adding a preset for a low quality/high performance visual settings would use less energy during long training sessions.

**Comment by IamEld3st** [comment]
You can speed up the game by changing game state. Here is python wiki for this feature https://github.com/RLBot/RLBotPythonExample/wiki/Manipulating-Game-State

**Comment by LeChosenOne** [comment]
Talking around the ML channel of the RLbot discord, users mentioned that you would have to also lock in the framerate to be a multiple of 60 to match the increase in the game speed. (ex: multiplying the game speed by 2 would require the game to run at 120 fps for the bot to be able to perform in a normal 60 fps environment). I feel like a simple GUI option that takes care of all of these factors would be nice. Also, I can't manually change the fps on rocket league past 120 or so, meaning I can't train bots past 2x speed. The only way to override this would appear to be a change in the RLbot framework, another reason why this should be done from the GUI and not programmatically in a bot agent.

**Comment by ddthj** [comment]
RLBotGUI can currently change game speed as a mutator. Bakkesmod would be the best workaround for speed control. At the end of the day a headless copy of the game would be needed to get any useful training speed, which is a WIP among some of the ML members.
