### ISSUE TITLE
BufferOverfilled when using C#

### ISSUE THREAD

**Issue by EBTheHero** [RLBot/RLBot#380]
A BufferOverfilled error has appeared when using C#.

The error was not present when I was testing my bot Febuary 19, 2pm est.
It is not present, Febuary 19, 9 pm.

~~The last changes of the framework between those times is the #378 commit. It is probable that the bug was caused by this change, but I can't make asumptions because I don't know the framework very well.~~
Lol scrap that it's probably the Friends Update I haven't noticed like a dumbass

The error occurs with the ExampleBot.

When launching, the first gameTickPacket sent contains a 0 player count, giving multiple errors if your code isn't well constructed against.

If it is, you get a BufferOverfilled error when setting the bot input.

I don't know enough about the framework, but here's a log. It occurs every tick or so when trying to load the game.

> BufferOverfilled
>    at RLBotDotNet.Utils.RLBotInterface.SetBotInput(Controller controller, Int32 index) in E:\Github\RLBot\src\main\cs\RLBotDotNet\RLBotDotNet\Interface\RLBotInterface.cs:line 151
>    at RLBotDotNet.BotManager`1.RunBot(Bot bot, AutoResetEvent botRunEvent) in E:\Github\RLBot\src\main\cs\RLBotDotNet\RLBotDotNet\Manager\BotManager.cs:line 98
> RLBotDotNet.Utils.RLBotCoreException

How to recreate:
1-install RLbot
2-Download the RLBotCSharpExample
3-update the RLBot NuGet
4-Start Rocket League, the bot and the GUI thingy
5-press run

It should give you an OutOfRange error, when trying to find a player at line 26 of ExampleBot.cs (and there's no bot in the gameTickPacket

6- surround the Try-Catch with if (gameTickPacket.PlayersLength > 1) {...}
so it doesn't give you an error
7- rebuild and run

Now, you should get the BufferOverfilled error.

**Comment by tarehart** [comment]
We're actually having a big problem with the new Rocket League patch that came out today, nobody is able to run bots at all right now. #378 tried and failed to fix it, we'll be trying again soon!

I'm guessing your problem is related to that, but let's follow up later. You can track our progress with the fix on discord. Sorry for the downtime!

**Comment by EBTheHero** [comment]
No problem

**Comment by TheBlocks** [comment]
Closing because this bug no longer happens.
