### ISSUE TITLE
Restarting runner will start a new match instead of continuing with the current one

### ISSUE THREAD

**Issue by TheBlocks** [RLBot/RLBot#401]
Restarting the runner (both runner.py and runner_gui.py) will start a new match instead of continuing with the current one.

**Comment by kipje13** [comment]
I don't actually mind this behaviour.

**Comment by DomNomNom** [comment]
The most recent version of RLBot makes this behavior configurable in the match config. 
Continuing if the match config is the same seems is the default IIRC.
Credit to @tarehart
