### ISSUE TITLE
State setting not working as before when given null values

### ISSUE THREAD

**Issue by TheBlocks** [RLBot/RLBot#402]
`null`/`None` will be replaced by `0` when using state setting. This is behaviour is breaking backwards compatibility. Before, using `null`/`None` for a value would not state set that component (instead of setting it to `0`).

**Comment by tarehart** [comment]
This is a limitation of the Psyonix API, but we might be able to hack around it in the short term.

**Comment by tarehart** [comment]
Hack is in place with 1.15.3, and working pretty nicely for Snek 👍
