### ISSUE TITLE
Bots don't respond after a goal is scored

### ISSUE THREAD

**Issue by robbai** [RLBot/RLBot#404]
Not critical, but between a goal being scored and the replay being shown, bots seem to not act properly, albeit momentarily

**Comment by tarehart** [comment]
Currently bot inputs are intentionally ignored by RLBot.exe during that time period, it improved stability at one point. Will experiment with removing that change to see if it's OK now.

**Comment by DaCoolOne** [comment]
On a related note, bots don't respond after a game is finished either. RIP my bot's celebrations :(

**Comment by NicEastvillage** [comment]
Beast does celebration on victory, so that part works again. Are inputs still ignored after goals?

**Comment by naturecodevoid** [comment]
Sort of, the bots continue using the same controller state when a goal is scored as before the goal was scored

So if the throttle was 1 and a goal was scored, the throttle will stay 1

**Comment by ddthj** [comment]
Last time I checked (right now), bots respond after goals are scored. Seems this issue is stale.
