### ISSUE TITLE
Dropshot and Hoops broken in new API

### ISSUE THREAD

**Issue by DaCoolOne** [RLBot/RLBot#405]
In the new official Psyonix API, when launching a game in the dropshot mode, the game loads into Core 707 with the default soccar game mode. This means that the boost is default instead of recharge and the tiles do not break when hit with the ball. Additionally, the ball is default rather than the dropshot ball. The ball also starts on the ground instead of flying into the air as would be expected in dropshot.

Many of the same issues also apply to hoops. The ball is the wrong type and does not fly into the air at the start of the match. However, scoring is possible in hoops, suggesting that the issue lies with the game starting state not being set properly.

**Comment by tarehart** [comment]
Fixed in version 1.15.2!
