### ISSUE TITLE
Human players not properly added to game tick packet

### ISSUE THREAD

**Issue by DaCoolOne** [RLBot/RLBot#406]
[PYTHON]
In the new Psyonix API, whenever a human player joins the match, the player is not properly added to the game tick packet. The packet.num_cars value is not updated to reflect the number of players, and even though a new car appears to be added to packet.game_cars, values such as location and velocity are not updated.

**Comment by dtracers** [comment]
Humans most be added via the rlbot GUI and can't join later.  This was also true with pre API. 
Though sometimes it did work by chance

**Comment by tarehart** [comment]
This is a valid issue that needs to be fixed. I don't believe the Psyonix API provides a way to make human players auto-join, so joining manually is the correct way of doing things now.

**Comment by DaCoolOne** [comment]
I'm getting conflicting messages, so I'll clarify.

Joining the game AFTER entering the match works, however the bot does not get the player's information (such as car location). HOWEVER, using the Human option in the rlbot GUI doesn't work with the new API (as far as I can tell).

**Comment by tarehart** [comment]
Yep, you and I are on the same page.

**Comment by tarehart** [comment]
I wrote a fix for this, I expect it to work properly in the next alpha release 👍

**Comment by tarehart** [comment]
Released. `pip install rlbot==1.15.0a2` to try it!

**Comment by DaCoolOne** [comment]
Just tested, and this issue appears to be fixed!

Hooray!

I believe that this issue can be closed now. Thanks tarehart!
