### ISSUE TITLE
Add New API FAQ

### ISSUE THREAD

**Issue by martmists** [RLBot/RLBot#407]
I'm sure people have a lot of questions, so adding a proper FAQ will be helpful, such as:

- Will I be able to play with friends now?
- Can bots play in the integrated Tournaments/Season after this?

Bot devs will also have some questions:

- What features will be added/removed?
- Will FPS setting still matter?
- Will bots be able to send custom quickchats now?
- Is the API reference publicly available anywhere?

It's best to answer questions like these on a separate, easy to find page on the wiki.

**Comment by skyborgff** [comment]
We are planning something like that, maybe a Q&A, but getting a question list now is good 😊

**Comment by tarehart** [comment]
This wiki can serve that purpose - https://github.com/RLBot/RLBot/wiki/Psyonix-API-Notes

I'll go ahead and answer your questions on it.
