### ISSUE TITLE
Rectangle rendering

### ISSUE THREAD

**Issue by 1JJensen** [RLBot/RLBot#409]
Rectangles are not being rendered in 1.15+.
You can still use strings and lines.

**Comment by tarehart** [comment]
We could make a ludicrous hack by:
- rendering a white space string with a background of the appropriate color
- scaled appropriately
- with a number of spaces designed to approximate the desired aspect ratio of the rectangle

**Comment by tarehart** [comment]
Ludicrous hack implemented in 1.16.3. Works surprisingly well. Closing.
