### ISSUE TITLE
If you try to spawn more than 4 bots on a team, the data packet indices go haywire

### ISSUE THREAD

**Issue by tarehart** [RLBot/RLBot#413]
Pictured: LethalLuck tried to play 1 human vs 8 AdversityBots. Only 4 spawned in (this is a known limitation of the psyonix API at the moment). The bots on the field kept perceiving an enemy player in the center of the field and trying to demo it.

![image](https://user-images.githubusercontent.com/575644/56639233-08dc7700-6625-11e9-8dd8-03ba7f7cab23.png)

**Comment by NicEastvillage** [comment]
Is this fixed?

**Comment by ViliamVadocz** [comment]
I have successfully ran >4 AdversityBots against >4 All-Stars without a problem. All bots spawned an there were no errors.

**Comment by tarehart** [comment]
Cool, I think this must be fixed. Thanks for testing Will
