### ISSUE TITLE
Ghost inputs

### ISSUE THREAD

**Issue by 1JJensen** [RLBot/RLBot#414]
While trying to fix my dodge code, I noticed that my bot was being interrupted by some weird behaviors from my bot. Without any yaw or roll ode my bot still managed to diagonal flip and even sideflip.

**Comment by martmists** [comment]
Ditto, can also confirm for other bots like Stick and I think Skybot had the same issue as well

**Comment by tarehart** [comment]
In Jonas' case, according to discord chat, it looks like his self.controller_state.yaw in his python bot was unexpectedly non-zero right before being returned from get_output. That sounds more like a bot-level bug than a framework bug.

Mart, can you give more specifics about what's going wrong with those bots?

**Comment by dtracers** [comment]
It was randomly side flipping when dodging instead of the correct which would imply that yaw was being sent instead of the correct output for the dodge.

**Comment by tarehart** [comment]
Jonas says the problem can be duped with this code: https://github.com/1JJensen/Trashbag/tree/580d42df51f869c7267855c416d603fef61a106c

**Comment by tarehart** [comment]
Likely fixed in version 1.15.8, where steer does not affect dodge direction.

**Comment by tarehart** [comment]
Closing, please reopen if you see evidence it's not fixed.
