### ISSUE TITLE
Find a way to launch with -rlbot option without confirmation popup

### ISSUE THREAD

**Issue by tarehart** [RLBot/RLBot#415]
Currently we launch with `webbrowser.open(f"steam://rungameid/{ROCKET_LEAGUE_PROCESS_INFO['gameid']}//-rlbot")` and it causes this Steam popup to open asking for confirmation:

![image](https://user-images.githubusercontent.com/575644/56709288-4d275000-66d5-11e9-87ee-c65829abf5a3.png)

Unfortunately it's often off-screen / minimized and doesn't give any audio or visual indication. This gives the sensation of rlbot getting stuck during launch for no reason, and it will cause ongoing pain.

Kipje says:
> launching Steam.exe from the command line with Steam.exe -applaunch 252950 -rlbot will start rocket league with "-rlbot"
without that anoying popup

**Comment by martmists** [comment]
There's a few issues with this solution:

- We would need the absolute path to Steam.exe, OR
- Steam needs to be in PATH, OR
- We need to bundle up to 6 versions of steam depending on host system.

Keeping in mind this needs to be cross-platform, I'm not sure how reliable that method is on Linux/MacOS.

**Comment by DomNomNom** [comment]
More options:

* Discover steam using OS specific methods and implement this for the different OSs.
* Somehow `webbrowser.open(f"steam://...)` maps onto some steam executable. We could investigate how that mapping works and see if we can get it from that to the steam.exe

**Comment by tarehart** [comment]
Fixed by @DomNomNom in 1.16.4. Closing!
