### ISSUE TITLE
Warn user that changing game speed is not currently supported when trying to set game speed

### ISSUE THREAD

**Issue by TheBlocks** [RLBot/RLBot#420]
Creating a GameInfoState object with game_speed should warn the user that changing game speed is not currently supported.

Currently RLBot does not tell the user that the game speed feature was dropped due to the new API. Adding this suggestion would cause less headaches for people unaware of the change.

This suggestion can be easily added by checking `if game_speed is not None` in GameInfoState `__init__`.

**Comment by tarehart** [comment]
I implemented this in RLBot.exe. Fixed as of 1.16.3, closing!
