### ISSUE TITLE
Unstable car state after state setting.

### ISSUE THREAD

**Issue by kipje13** [RLBot/RLBot#422]
See this clip: https://gfycat.com/CluelessPettyJunco

This happens even after setting the car state to a motionless state:
```
carstate.physicsState.location = { 0, 0, 18 };
carstate.physicsState.velocity = { 0 , 0, 0 };
carstate.physicsState.angularVelocity = { 0 , 0, 0 };
carstate.physicsState.rotation = { 0, PI/2, 0 };
```
C# and C++ both show the same behaviour.

After some further experimenting it seems that sometimes the angular velocity along the world x-axis gets set.

**Comment by alion02** [comment]
Temporary solution for some use cases is to repeat state setting until it works properly (which in my case seems to be just 2 times). As for the issue itself, to me it looks like the current car velocity somehow gets tangled up in the desired angular velocity, desired rotator or both.

**Comment by samuelpmish** [comment]
All my python examples are broken at the moment because of this, is it being looked into or should python developers implement a workaround?

**Comment by tarehart** [comment]
I'm not looking into it at the moment. I think I ruled out errors on our end, my next step is to double check, and gather good data to show to Psyonix.

**Comment by samuelpmish** [comment]
thanks for the update

**Comment by tarehart** [comment]
We think this might be fixed; our two methods of reproducing this issue are now showing no problems. Is anybody still seeing this?

**Comment by ddthj** [comment]
"We think this might be fixed"
I deem it fixed until more noise is made about it
