### ISSUE TITLE
SecondsElapsed and GameTimeRemaining

### ISSUE THREAD

**Issue by alion02** [RLBot/RLBot#423]
SecondsElapsed keeps running while the game is paused and GameTimeRemaining has an integer precision.

**Comment by DaCoolOne** [comment]
Also have this issue in Python. Would be nice if I could tell when the game is paused or if SecondsElapsed didn't update when game is paused.

**Comment by tarehart** [comment]
We should be capable of fixing this the next time a Rocket League patch comes out.

Currently, SecondsElapsed is telling you the number of seconds (on the wall clock, I think) since Rocket League was launched. That's not intended, but maybe that's helpful to know until we can get this fixed.

**Comment by alion02** [comment]
Appreciate it! Detecting game pausing becomes way more hacky without this feature, and is quite crucial for general-purpose bots.

**Comment by tarehart** [comment]
Turns out a patch just came out recently. Fixed in rlbot 1.18.1!
