### ISSUE TITLE
Score info not working

### ISSUE THREAD

**Issue by gjossep** [RLBot/RLBot#429]
When trying to run this, Im printing out all the values that are sent in the get_output()

This seems to work except for the score info. All values inside that table stay at 0 and do not change.

Below is the output of all the print statements, at the time the bot itself had around a score of 600 and scored twice.

`Vector3<x: -2631.56005859375, y: 3886.969970703125, z: 17.059999465942383>
Rotator<pitch: -0.009587380103766918, yaw: 1.436381220817566, roll: 0.0>
Vector3<x: 190.51100158691406, y: 1014.8909301757812, z: -0.5509999990463257>
Vector3<x: 0.0, y: 0.0, z: 2.338209867477417>
ScoreInfo<score: 0, goals: 0, own_goals: 0, assists: 0, saves: 0, shots: 0, demolitions: 0>
False
True
False
True
False
False
PythonExampleBot
0
100`

**Comment by naturecodevoid** [comment]
Is your bot doing anything that will get it points?

**Comment by gjossep** [comment]
Yes, Its scoring, touching the ball, etc. Even if it scores the value of the goal stays at 0.

**Comment by naturecodevoid** [comment]
Weird.

**Comment by naturecodevoid** [comment]
You're getting the info every `get_output`, right? You might want to restart the gui/framework.

**Comment by kipje13** [comment]
Unfortunatly this is something that broke after we switched to the Psyonix API.

**Comment by naturecodevoid** [comment]
Ok. gjossep might want to close this then.

**Comment by gjossep** [comment]
> Unfortunatly this is something that broke after we switched to the Psyonix API.

Is there any plans to get it fixed?

**Comment by kipje13** [comment]
Not yet, you are the first to mention this problem. 

> Ok. gjossep might want to close this then.

We can leave this issue open. It is a nice reminder for us that we still not to look into this problem.

**Comment by frederikmartin** [comment]
I've got the same problem. ScoreInfo is filled with 0 values and not updating during game play.

**Comment by tarehart** [comment]
Score info is fixed now!
