### ISSUE TITLE
Prediction struct missing data in the last slice (Python)

### ISSUE THREAD

**Issue by ddthj** [RLBot/RLBot#431]
After calling agent.get_ball_prediction_struct and looking at the last slice via prediction.slices[prediction.num_slices]) I found that the slice was empty. The game_seconds for this slice is 0.0 and the physics vectors are all populated with 0's.

**Comment by tarehart** [comment]
Is that what your actual code looks like? One would do prediction.slices[prediction.num_slices - 1] to get the last slice (or `prediction.slices[-1]`).

Based on my testing, num_slices has been reliable. It tends to be 359 which probably feels odd, but that's not the bug described here.

**Comment by ddthj** [comment]
prediction.slices[prediction.num_slices-1] and prediction.slices[-1] return different results. There may be only 359 slices however the list is 360 slices long with the last slice being all zeros

**Comment by dtracers** [comment]
in python you should do num_slices.  (for all lists)

because in python we do native c structs ALL lists are a fixed size.
These fixed sizes can be much longer than how many items are actually within as some are very dynamic lists.

**Comment by tarehart** [comment]
Oh right, my bad. Always `prediction.slices[prediction.num_slices-1]`.

In other news, num_slices should now be 360 as of rlbot 1.18.1, so prediction.slices[-1] will work even though it's dangerous and a bad idea.
