### ISSUE TITLE
Sometimes the player is put into the match but is stuck on the choose team screen.

### ISSUE THREAD

**Issue by ViliamVadocz** [RLBot/RLBot#436]
The user can't join the team they are on and have to join the other team or spectate and then go back.

![image](https://user-images.githubusercontent.com/26529068/61399830-3efd6000-a8cf-11e9-9272-a8d61392e077.png)

**Comment by ddthj** [comment]
This is a common bug, with the temporary workaround being to join the opposite team and then switch back.

**Comment by ddthj** [comment]
Fixed/Stale
