### ISSUE TITLE
Match does not start if the player is already in an exhibition match.

### ISSUE THREAD

**Issue by ViliamVadocz** [RLBot/RLBot#437]
If the player is in an exhibition match and tries to start a match in the GUI, the match doesn't start and the bots don't spawn, but things such as the BotHelperProcess start.

**Comment by kipje13** [comment]
I assume this happens when you started the match by yourself instead of letting the framework handle that.

What happens when you set the framework to always restart the match? 

You can do this by going to "Extra" and setting "Existing match behaviour" to "Restart".

**Comment by ViliamVadocz** [comment]
Your assumption was correct, sorry for not specifying.
When I set the "Existing match behaviour" to "Restart", it worked as expected and a new match with the bots began.

**Comment by ddthj** [comment]
"it worked as expected." Redox why'd you add the bug label if this was fixed? inb4 I misread something.
