### ISSUE TITLE
Rendering manager sends `bad status BufferOverfilled` when moving the RL window around.

### ISSUE THREAD

**Issue by ViliamVadocz** [RLBot/RLBot#438]
When you move the Rocket League window while a bot is trying to render, the console will be spammed with `ERROR:Renderer[rendering_manager.py:49 -           send_group() ] bad status BufferOverfilled`.

![image](https://user-images.githubusercontent.com/26529068/61476735-fbb5f680-a98d-11e9-8df1-364618508442.png)

**Comment by kipje13** [comment]
Moving or resizing the Rocket League window will freeze the game.
It is possible that render messages will not get processed when this happens.

Most likely the best solution is to just not move or resize the window.

Have you noticed anything breaking or is it just these messages?

**Comment by ViliamVadocz** [comment]
Seems like just messages. It just spams the console so it is slightly annoying.

**Comment by tarehart** [comment]
I'll probably suppress that error message soon, I don't think it's ever done any good.

**Comment by TheBlocks** [comment]
Has this been fixed?

**Comment by ViliamVadocz** [comment]
@TheBlocks I can't reproduce it any more. It might have been fixed, or maybe tare just suppressed the message.

**Comment by ddthj** [comment]
Sounds fixed/stale to me!
