### ISSUE TITLE
Rocket League closes when the user closes the RLBot command prompt.

### ISSUE THREAD

**Issue by kipje13** [RLBot/RLBot#439]
Reported by multiple users after the 1.22.1 update. Happens with the both the new and old GUI.

This is extremely annoying because I occasionally need to restart the framework. Now I have to wait for my game to close and restart.

**Comment by tarehart** [comment]
I don't see this happening after your 1.22.2 deployment, is it possible it got fixed?

**Comment by TheBlocks** [comment]
It's been a while since this issue was opened. I don't see this behaviour at the moment. Has this been fixed?

**Comment by ddthj** [comment]
Appears Fixed.
1. Launched match
2. Waited for countdown
3. Closed cmd
4. Game remained open, bots used their last control input.
