### ISSUE TITLE
packet.game_ball.last_touch object has no attribute 'player_index'.

### ISSUE THREAD

**Issue by oxrock** [RLBot/RLBot#440]
This error is with a python agent. last_touch.player_name, hit_location and team are being accessed without issue but "last_touch.player_index" errors without fail.

**Comment by tarehart** [comment]
In discord, Kipje says this works for him:
```
if (packet.game_ball.latest_touch.time_seconds == packet.game_info.seconds_elapsed):
    print(packet.game_cars[packet.game_ball.latest_touch.player_index].name)
```

Can you please confirm what RLBot version you're on?

**Comment by oxrock** [comment]
using version 1.23.0 currently

using rlbot.utils.structures.game_interface.GameInterface to update the packet for a non agent bot to cast the games. I'm assuming perhaps it's not behaving quite the same way as a bot's method of obtaining packet data.

snippet used to obtain packet with missing player_index data for ball.latest_touch:
packet = GameTickPacket()
self.game_interface.update_live_data_packet(packet)

**Comment by oxrock** [comment]
issue caused by outdated rlbot installation due to not having updated my personal python installation's rlbot in a while. Apologies.
