### ISSUE TITLE
New GUI sometimes fails to open with "cannot import name 'lib' from 'numpy'"

### ISSUE THREAD

**Issue by dtracers** [RLBot/RLBot#441]
If we have a bot that is dependent on a library that is not installed we can't load the GUI to install it. We should load anyways with errors so that we can install packages

**Comment by kipje13** [comment]
Bots get loaded after you hit the "start match" button so you should always be able to open the GUI when bots are missing packages.

**Comment by tarehart** [comment]
Yep, bot-specific dependencies are not the root cause here. I'm going to re-title this issue accordingly. Here's the symptom:

![image](https://user-images.githubusercontent.com/575644/62545553-c7a85580-b816-11e9-8338-683a7d647c1a.png)

**Comment by tarehart** [comment]
Every time a user opens the GUI, we install or update the dependencies needed for rlbot, rlbot_gui, etc. The first time this is done after installation of the GUI, many are installed including numpy. This is the output from a successful installation:

![image](https://user-images.githubusercontent.com/575644/62546490-6c776280-b818-11e9-9402-3c6d416a7a1f.png)

For the user where the GUI is failing, something probably went wrong during the numpy installation (didn't get identified as a dependency? incomplete download? incomplete installation?). We don't have enough info yet to guess.

**Comment by ddthj** [comment]
This is starting to smell stale. In case it's not, my best guess is that sometimes pip shoots itself in the foot, which is a problem I've recently made a wiki entry for. https://github.com/RLBot/RLBot/wiki/Troubleshooting#after-install-rlbot-doesnt-open-gets-stuck-updatingcollecting-packages
