### ISSUE TITLE
Console spams no support for setting gravity or game speed when they aren't being state set

### ISSUE THREAD

**Issue by TheBlocks** [RLBot/RLBot#443]
Related to issue #420.

The following code is spammed in the console when state setting: `We don't support setting gravity or game speed at this time, sorry!`. However, neither gravity nor game speed are being set.

The following C# code triggers it:
```csharp
SetGameState(new GameState
{
    BallState = new BallState(new PhysicsState(new DesiredVector3(0, 5500, 100)))
});
```

**Comment by ddthj** [comment]
As someone who has done a lot of state-setting recently, this smells stale. Perhaps exclusive to c#?

**Comment by TheBlocks** [comment]
I can no longer reproduce this error. Also, that error text doesn't appear in any part of the codebase so it wouldn't make sense for that error to be logged in any language.
