### ISSUE TITLE
Periodic bursts of inconsistent timing for get_output calls at 120fps

### ISSUE THREAD

**Issue by ericmburgess** [RLBot/RLBot#445]
(Possibly related to #358)

With FPS set to 120 in `TARLBot.ini`, the expected game time delta between calls to my Python bot's `get_output` is 8.33ms. However, when tracking the rate of bad frames (those with a different game time delta), I see that there are a lot of them, and they come in [periodic bursts](https://cdn.discordapp.com/attachments/348659150793736193/613526304171622410/unknown.png).

My hunch is that the root cause is that two processes (the game physics update and the polling of it) are running at an almost identical 120Hz frequency, so that they slowly come [in and out of phase](https://en.wikipedia.org/wiki/Beat_(acoustics)). When they're nearly in phase, a tiny variation in timing can cause the events to happen in the wrong order, so a tick gets repeated or skipped.

I made an experimental "adaptive" rate limiter that uses feedback about game time deltas to attempt to stay out of phase with the game update. It doesn't show a periodic pattern, and the overall percentage of bad frames (on my machine) is reduced from 4.5% to about 0.18%. I'm now hoping others will try to confirm the existing behavior, and if they can, maybe try out my solution.

**Comment by L0laapk3** [comment]
for completeness, I'd like to point out that while this looks like something else, theres also all kinds of weirdness with dropped ticks when rocket leagues fps is not capped to exactly 120. I've updated [the wiki page](https://github.com/RLBot/RLBot/wiki/Tick-Rate) with my findings. tl;dr is that when RL fps is not always exactly 120, packetSendRate from TARLBot.ini should be set to at least 240 to avoid dropped ticks.

**Comment by NicEastvillage** [comment]
Has since been fixed
