### ISSUE TITLE
Gui will not install if user has utf8 character in name.

### ISSUE THREAD

**Issue by DaCoolOne** [RLBot/RLBot#449]
Discovered when someone in the discord had an ñ character in their windows path name. This caused the entire GUI to not install.

https://cdn.discordapp.com/attachments/348659150793736193/621479174900547614/unknown.png

**Comment by DaCoolOne** [comment]
https://discordapp.com/channels/348658686962696195/348659150793736193/621479175399931934

**Comment by martmists** [comment]
This is easily solved by adding `chcp 65001` to the .bat files that could potentially trigger this
