### ISSUE TITLE
Linux - RLBot Fails to Connect listening to port

### ISSUE THREAD

**Issue by JunkyByte** [RLBot/RLBot#450]
**Issue:**
Occasionally RLBot successfully launches the game but fails to connect, leaving the game in the menu.
Trying to kill the process using `Ctrl+C` Does not work and returns the message
`Trying to connect to Rocket League on port xxxxx...`

Reproducing the issue is not immediate as it seems to happen at random, it still happen 1 out of ~5 times.
Whenever it does happen killing and relaunching the RLBot process in a new terminal does not seem to work and you have to manually close the Game before trying again

**Comment by VirxEC** [comment]
If you're still having issues, please visit the #issues-and-bugs channel in our [Discord server](https://discord.com/invite/nhdwbSz) for help.
