### ISSUE TITLE
Linux - occasionally Game gets killed

### ISSUE THREAD

**Issue by JunkyByte** [RLBot/RLBot#451]
**Issue:**
Sometimes after killing the RLBot which is communicating successfully with the game, the game closes after some random amount of time.
It happens only occasionally so I assume this is not the intended behavior.
Also the time before the game is killed is not constant, sometimes it happens as soon as the RLBot is terminated, other times it takes minutes.

**Comment by VirxEC** [comment]
If you're still having issues, please visit the #issues-and-bugs channel in our [Discord server](https://discord.com/invite/nhdwbSz) for help.
