### ISSUE TITLE
Running two matches in a row causes Java bots to run slow

### ISSUE THREAD

**Issue by robbai** [RLBot/RLBot#460]
Using the 1.9.1 Gradle release, when running a second match in a row without terminating the Java processes in between, the Java bots run at around 1% for the first 30-60 seconds of the match, tested with both 60Hz and 120Hz on my bot which didn't have this issue before the update

**Comment by tarehart** [comment]
Using print statements, I did observe an urgency of -580 after a game ended. I think @Godsoft029 has an accurate diagnosis, and it does behave exactly the same as if the game had been paused.

**Comment by tarehart** [comment]
Java's rlbot-framework 1.10.1 is now published, hopefully fixing this issue.
