### ISSUE TITLE
Rlbot hates Numba

### ISSUE THREAD

**Issue by oxrock** [RLBot/RLBot#464]
@jit even the simplest functions within an rlbot loaded script and it'll throw several pages of errors. This is even more proof that you devs hate python users, prove me wrong!

**Comment by TheBlocks** [comment]
Specifying the type signatures makes Numba work with RLBot, so I'm closing this issue.

Lazy mode does not work and you must specify the types yourself.
```
@jit(f8(f8, f8))
def multiply(a,b):
    return a*b
```


References:
- https://discordapp.com/channels/348658686962696195/446761380654219264/680511446630531088
- https://discordapp.com/channels/348658686962696195/446761380654219264/680733519336439841
