### ISSUE TITLE
has_wheel_contact needs to be debounced 

### ISSUE THREAD

**Issue by ddthj** [RLBot/RLBot#465]
In its current state, has_wheel_contact is set to False when a bot jumps. There are 2-3 frames where it can briefly become True again before the bot has actually cleared the ground.

This may explain why older bots sometimes dodge randomly. If a bot presses jump while it has_wheel_contact, and the value bounces in the 2-3 frames after the jump is pressed, the bot may inadvertently release the jump button and press it again, causing a dodge.

**Comment by tarehart** [comment]
Good catch! Fixed for windows by Kipje in 1.34.4. Will be fixed for Linux and Mac when somebody gets around to recompiling those.
