### ISSUE TITLE
maximum pitch, yaw, and roll?

### ISSUE THREAD

**Issue by jball1997** [RLBot/RLBot#468]
What are the maximum and minimum values for pitch, yaw, and roll?

**Comment by robbai** [comment]
Pitch ranges from -pi/2 to pi/2
Yaw ranges from -pi to pi
Roll ranges from -pi to pi

If you haven't already, I recommend joining the [Discord](https://discord.gg/zbaAKPt), it is generally the better place for asking questions

**Comment by jball1997** [comment]
Thanks I will!
