### ISSUE TITLE
Stuck without wheel contact

### ISSUE THREAD

**Issue by robbai** [RLBot/RLBot#475]
Bots like ReliefBot and Anarchy have been spotted on Redox's stream stuck in their recovery state, since the wheel contact is frozen as False.
Seemed to be fixed by restarting RLBot.

**Comment by tarehart** [comment]
Thanks for reporting, I have an idea of what might be wrong.

**Comment by tarehart** [comment]
Likely fixed in 1.35.4, just deployed. Will close this tomorrow if we hear no more reports.
