### ISSUE TITLE
Add flexibility to agent loading so agents can be stored outside RLBot folder / so bot makers can use gradle dependency on framework

### ISSUE THREAD

**Issue by tarehart** [RLBot/RLBot#48]
Currently agent py files need to be placed somewhere inside the RLBot folder, otherwise `# Path to module from runner` in the agent's cfg file won't work

I don't like that situation because I want to put my bot in its own repository outside the RLBot folder, and not need to copy files over

I think @DomNomNom achieved that flexibility once, then it was broken, now I want to bring it back again. Dom's commit: https://github.com/RLBot/RLBot/commit/10e1e0612ba30c5cdcf691e4e3ff7a40414858f2

One of my constraints will be that v1 and v2 of a python bot should be easy to fight against each other without part of their imports conflicting

From Marvin:
About the pathing issue not sure if you're aware but it's not necessary to add the folder to sys path, you could use importlib spec to import from a path
You can check this commit for reference
https://github.com/RLMarvin/RLBot/commit/2ad7230a53ad1745ec0ed19b8f22e70c33df8385
I was using two paths one for the agent and one for the cfg but if you assume they are in the same directory you can simply use one
This will make it possible to have the agent outside runner.py folder and fix imports with multiple agents having the same name

**Comment by dtracers** [comment]
Currently the gui does assume 2 paths.
But it imports it from the config by default.
I think we could also do it where if a path does not exist in the config then we can add it

**Comment by dtracers** [comment]
https://github.com/RLBot/RLBot/blob/v4/RLBotFramework/utils/class_importer.py

Changes should take place in this file only,
Also note that it does have some code to take out the raw path by removing it from the repo path. (used in gui)
That will end up breaking by these changes so we will have to account for that

**Comment by tarehart** [comment]
I'm considering replacing our custom_config module with this project:
http://configobj.readthedocs.io/en/latest/configobj.html

**Comment by tarehart** [comment]
Took care of this with #50
