### ISSUE TITLE
State setting does not work with python 3.8

### ISSUE THREAD

**Issue by ViliamVadocz** [RLBot/RLBot#505]
The console printed `Ignoring state setting attempt because it's disabled` even though the match config file was correct (state setting enabled) and everything else was properly restarted.

As soon as python 3.7 was tried instead of 3.8, it worked. This is the end of the conversation, although some of it was in voice chat: https://discordapp.com/channels/348658686962696195/348659150793736193/715266063901917195

To reproduce:

1. Install Python 3.8
2. Run a match with state setting enabled (using local python install)
3. Use a bot that state sets

**Comment by ViliamVadocz** [comment]
To run the match with the local python installation, you could use the old gui or this:

```py
from rlbot.setup_manager import SetupManager

manager = SetupManager()
manager.load_config(config_location=YOUR CONFIG LOCATION HERE)
manager.connect_to_game()
manager.launch_early_start_bot_processes()
manager.start_match()
manager.launch_bot_processes()

# maybe some timeout
# manager.shut_down(kill_all_pids=True)
```

**Comment by tarehart** [comment]
Discord user Zilch hit this recently and it caused a lot of pain

**Comment by tarehart** [comment]
I now believe that the real problem is 32 bit python. I have not recompiled the 32 bit dll since January, which was before the state setting flag was introduced.
