### ISSUE TITLE
RLBot.exe not found

### ISSUE THREAD

**Issue by Vasecarpet124** [RLBot/RLBot#512]
![image](https://user-images.githubusercontent.com/50207878/86520474-92e4ba00-be3c-11ea-849d-4df8865d6414.png)
so i tried starting the match but it came up with this ^ in the console and it didn't start the match. (i disabled my antivirus)
then i tried to go to "C:\Users\MYNAME\Appdata\Local\RLBotGUIX\venv\lib\site-packages\rlbot\dll" and i saw 
![image](https://user-images.githubusercontent.com/50207878/86520522-42219100-be3d-11ea-88dc-1b19257fca07.png)
![image](https://user-images.githubusercontent.com/50207878/86520534-5ebdc900-be3d-11ea-8d94-e5d2f5d75b71.png)
![image](https://user-images.githubusercontent.com/50207878/86520540-709f6c00-be3d-11ea-825e-3d16e545c931.png)
so then i though "oh i should turn it into an exe" and that's what i did. 
![image](https://user-images.githubusercontent.com/50207878/86520551-a2b0ce00-be3d-11ea-9cd2-70f2317dfe0b.png)
and then 
![image](https://user-images.githubusercontent.com/50207878/86520559-be1bd900-be3d-11ea-8c48-36ed3876d392.png)
...
it still didn't start the match so i looked in the console 
![image](https://user-images.githubusercontent.com/50207878/86520573-e99ec380-be3d-11ea-9a35-b40fbc597c34.png)
![image](https://user-images.githubusercontent.com/50207878/86520599-3b474e00-be3e-11ea-941c-24d802f2bdc7.png)

**Comment by ViliamVadocz** [comment]
You should join the discord and someone will help you out in #issues-and-bugs
I expect that to be a quicker way to get help than through github.

**Comment by tarehart** [comment]
Hey sorry you're having trouble!

That was a good try with the .exe thing, but that RLBot file is actually intended for Linux users and is intended to have no extension (for better or worse). It looks like your original RLBot.exe is missing for whatever reason.

It's usually antivirus. I know you said you turned it off, but the damage is probably already done, so you may need to take a look at https://github.com/RLBot/RLBot/wiki/Antivirus-Notes and reinstall.

**Comment by azeemba** [comment]
This was resolved and confirmed in the discord chat.
