### ISSUE TITLE
rlbot not running with required arguments

### ISSUE THREAD

**Issue by EshanTahir** [RLBot/RLBot#519]
It isn't running with required arguments? I have no access to discord, please help me here. I tried adding the launch arguments manually, it worked before, but then the update changed the launch arguments. Thanks!
![Capture](https://user-images.githubusercontent.com/43732685/88245159-14718000-cc64-11ea-84c2-11c525b09e2b.PNG)
![Captu1re](https://user-images.githubusercontent.com/43732685/88245160-150a1680-cc64-11ea-94b1-8cb32489008b.PNG)

**Comment by azeemba** [comment]
Do you mind adding a screenshot or the text of the error you are seeing?

**Comment by EshanTahir** [comment]
![Capture](https://user-images.githubusercontent.com/43732685/88244242-3b7a8280-cc61-11ea-9526-b6d7937c3122.PNG)

**Comment by EshanTahir** [comment]
![Captu1re](https://user-images.githubusercontent.com/43732685/88244489-00c51a00-cc62-11ea-99d8-c0d9cbc6b933.PNG)

**Comment by tarehart** [comment]
Thanks for the screenshots! We ask you to start out with rocket league closed and let RLBotGUI open it for you. Then the arguments will automatically be correct.

**Comment by EshanTahir** [comment]
Ive tried that, I have a custom unofficial install

**Comment by EshanTahir** [comment]
it is not a steam app, so rlbot cant change the arguments.

**Comment by tarehart** [comment]
Try replacing [0-9]+ with 23233

**Comment by EshanTahir** [comment]
Nope, did not work.

**Comment by tarehart** [comment]
It should look like this:

`-rlbot RLBot_ControllerURL=127.0.0.1:23233`

**Comment by EshanTahir** [comment]
It still didn't work. here's the error, (rocket league isn't open at the time I try to launch with rlbot)
 raise WrongProcessArgs(f"{program} is not running with required arguments: {required_args}!")
rlbot.utils.process_configuration.WrongProcessArgs: RocketLeague.exe is not running with required arguments: {'RLBot_ControllerURL=127.0.0.1:[0-9]+', '-rlbot'}!

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "src\\gevent\\greenlet.py", line 854, in gevent._gevent_cgreenlet.Greenlet.run
  File "C:\Users\pure8\AppData\Local\RLBotGUIX\venv\lib\site-packages\rlbot_gui\match_runner\match_runner.py", line 172, in start_match_helper
    sm.connect_to_game()
  File "C:\Users\pure8\AppData\Local\RLBotGUIX\venv\lib\site-packages\rlbot\setup_manager.py", line 170, in connect_to_game
    elif not self.is_rocket_league_running(port):
  File "C:\Users\pure8\AppData\Local\RLBotGUIX\venv\lib\site-packages\rlbot\setup_manager.py", line 147, in is_rocket_league_running
    raise Exception(f"Rocket League is not running with {ROCKET_LEAGUE_PROCESS_INFO.REQUIRED_ARGS}!\n"
Exception: Rocket League is not running with {'RLBot_ControllerURL=127.0.0.1:[0-9]+', '-rlbot'}!
Please close Rocket League and let us start it for you instead!
2020-07-23T01:53:06Z <Greenlet at 0x1bce95b1e18: start_match_helper([{'name': 'Human', 'team': 0, 'type': 'human', 'sk, {'map': 'NeoTokyo', 'game_mode': 'Soccer', 'skip_r)> failed with Exception

**Comment by tarehart** [comment]
Sorry it didn't work. What's the nature of your custom unofficial install / why are you in that situation?

**Comment by EshanTahir** [comment]
Well... I have not bought the game, I installed it for free( i am young and can't pay for it). But it is the latest version of the game. And rlbot has been working until the update a few days ago.

**Comment by tarehart** [comment]
Got it. I think you'll need to wait until Rocket League becomes free to play later this summer, sorry.

**Comment by EshanTahir** [comment]
How will that fix the problem? rlbot was working until the rlbot update.

**Comment by EshanTahir** [comment]
That must mean rlbot is the problem?

**Comment by tarehart** [comment]
It might not fix the problem automatically, but I'm not interested in supporting unofficial copies of the game. We don't condone breaking the Psyonix terms of service. Once you have a legit copy, if the problem is still happening, I'll be happy to put in effort to get you fixed up.

**Comment by EshanTahir** [comment]
Ok, Thanks!
