### ISSUE TITLE
Don't use requirements.txt to express a need for tkinter

### ISSUE THREAD

**Issue by tarehart** [RLBot/RLBot#525]
https://discord.com/channels/348658686962696195/348661571297214465/747002078446223390

When you try to `pip install -r requirements.txt`, it fails if you have tkinter in there. I didn't think of that when I made custom code that parsed requirements to notice and warn about missing tkinter.

Instead, we should probably make a flag in bot.cfg files where you can specify that tkinter is needed.

**Comment by VirxEC** [comment]
I think that flat in bot.cfg would be the best option
