### ISSUE TITLE
GUI takes too long to start when there is no internet connection

### ISSUE THREAD

**Issue by ddthj** [RLBot/RLBot#530]
Expected behavior: Without internet the GUI launches immediately without updating

Actual Behavior: The libraries attempt to update and time out 4 times each, which takes a couple minutes. 

Reproduction: Disconnect from the internet and launch RLBotGUI

**Comment by VirxEC** [comment]
I’ll start looking for a solution - I’ll prob just ping google, and if I can, check for updates

**Comment by VirxEC** [comment]
Also, why is this on the RLBot repo and not the RLBotGUI repo!?

**Comment by ddthj** [comment]
oopsie
