### ISSUE TITLE
Rendering should be on by default for new RLBotGUI installations.

### ISSUE THREAD

**Issue by tarehart** [RLBot/RLBot#549]
We get a lot of confusion from new botmakers about why their rendering isn't working, since it's off by default.

Previously we got a lot of questions from casual users wanting to disable it. Render instructions for turning it off with PgDown during the beginning of the match.

**Comment by azeemba** [comment]
I guess this goes back to the question of who our primary target audience is. This plan makes sense for botmakers but it's a worse experience for bot consumers. 

I think a botmaker is engaged enough by the time they need rendering that increasing that burden is only a slight increase. So I would consider leaving that behavior as is

**Comment by tarehart** [comment]
Fair point, we should consider alternative solutions too. If the 'new bot' functionality in the GUI took the liberty of turning rendering on, that might at least cover the Python crowd. Maybe some code comments in the example bots would help also.

**Comment by ddthj** [comment]
I think it should default to off, but all the rendering documentation should contain a reminder to turn it on.

**Comment by NicEastvillage** [comment]
I also believe that it should be off by default since we have more bot players than bot makers. Bot makers will most likely find the rendering documentation so putting a note there on how to toggle it (which I did yesterday) should cover most cases.
