### ISSUE TITLE
RLBotGUI won't start match

### ISSUE THREAD

**Issue by ElemehNough** [RLBot/RLBot#588]
I was playing earlier and it was working fine. I went to lunch and switched the car to the Z and have been getting this error since. Even after switching back to the Octane, Uninstall/re-install Python and RLBot, and restarting PC.
![image](https://user-images.githubusercontent.com/106934560/172073869-b4dac040-08f7-44b4-bb08-2a22bcf13fb1.png)

**Comment by Darxeal** [comment]
The car is irrelevant. The error is pretty clear, RLBot.exe got deleted, probably by your antivirus. You have to add an exception in your antivirus and then reinstall rlbot.
