### ISSUE TITLE
How to trade??

### ISSUE THREAD

**Issue by YahiaGamer** [RLBot/RLBot#598]

**Comment by VirxEC** [comment]
RLBot can not do trading, which is against Rocket League's ToS, and can get you banned.

**Comment by YahiaGamer** [comment]
oh sry i dont know but every rl store use a trade bot so why they didnt got banned?

**Comment by VirxEC** [comment]
It's only a matter of time before the bots get banned but they just create new free accounts. But that's not what RLBot is for, regardless.

**Comment by redd-rl** [comment]
They're probably talking about the discord bots.
