### ISSUE TITLE
Bot doesn't move

### ISSUE THREAD

**Issue by olikam0712** [RLBot/RLBot#599]
When I start a game the game opens and everything but the bot is not moving and i get and error in the console:
<img width="914" alt="Bildschirmfoto 2022-10-10 um 20 08 41" src="https://user-images.githubusercontent.com/71721386/194928118-77549302-f446-461e-8059-d2eea6457a91.png">

**Comment by VirxEC** [comment]
Hello, please join our discord and provide more details there -> https://discord.gg/zbaAKPt
