### ISSUE TITLE
Bots don't spawn in LAN matches

### ISSUE THREAD

**Issue by StressDad** [RLBot/RLBot#602]
Have followed all tutorial and everything is correct and working for solo play, but when I quit to main menu and start a LAN match with Rocket Plugin, the bots do not spawn. Any ideas?

**Comment by VirxEC** [comment]
https://github.com/RLBot/RLBot/wiki/LAN-Setup

IF that doesn't work, please join our discord and provide more details there -> https://discord.gg/zbaAKPt
