### ISSUE TITLE
Rendering strings (text) no longer works if scale_x or scale_y is set to 1

### ISSUE THREAD

**Issue by goteppo** [RLBot/RLBot#604]
Hi there. Sometime in the past few months rendering strings (both 2D and 3D) stopped working in my own bots as well as all the other bots I had been playing against that also print out their own debug information (e.g. Self-Driving Car). This applies to bots written in different languages (e.g. mine is in Go, while Self-Driving Car is written in Python I believe).

By pure luck I just happened to try changing scale_x and scale_y parameters in my code, and lo and behold, it turned out that with values 2 or higher the string rendering works normally, but changing them back to 1 disables the rendering of those strings again.

What is strange though, is that the issue started months ago if I recall correctly (at minimum it's been many weeks), yet I haven't heard of anyone else being affected by it even after asking on Discord. Has anyone else here seen this same issue, or able to reproduce it?

**Comment by goteppo** [comment]
Looks like the issue is resolved. If that was due to an update in RLBot, then thank you very much, it is greatly appreciated.

I did however switch computers too (about a week ago) and did not pay attention whether the text rendering issue was still happening on the new computer too. So, there may be a small possibility that the whole issue was somehow happening only on my old computer.

**Comment by goteppo** [comment]
Seeing the issue again. Not sure what's going on...

**Comment by goteppo** [comment]
Ah, I finally figured out why the problem appear and disappears. It depends on the resolution in the video settings (something I keep changing when I work on a laptop with no external monitor).

For example, if I change my Rocket League Video settings to Windowed w/ resolution 1280x720, then the text disappears completely. But in Fullscreen mode or Windowed w/ resolution 1600x900 the text appears normally.

So, now I know how to avoid the problem, but not sure if I should leave the issue open or closed?

**Comment by NicEastvillage** [comment]
Interesting. I have not heard of this problem before. Does the text disappear or is it perhaps just offscreen? I think you should create a new issue if the problem continues.
