### ISSUE TITLE
I get this message when launching

### ISSUE THREAD

**Issue by Tea69420** [RLBot/RLBot#607]
No module named pip
'"Python37\Scripts\pip.exe"' is not recognized as an internal or external command,
operable program or batch file.
'"Python37\Scripts\pip.exe"' is not recognized as an internal or external command,
operable program or batch file.
'"Python37\Scripts\pip.exe"' is not recognized as an internal or external command,
operable program or batch file.
Launching RLBotGUIX!
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'rlbot_gui'
Press any key to continue . . .

**Comment by zouser67** [comment]
restart your pc

**Comment by VirxEC** [comment]
Hello, the solution in pinned in our discord -> https://discord.gg/zbaAKPt
