### ISSUE TITLE
Story Mode Problem

### ISSUE THREAD

**Issue by jbrain121** [RLBot/RLBot#609]
Hello I am attempting to playthrough the story mode on RLBOT and when attempting to play the match titled "How does the car turn so fast" it fails and gives an error in the console reading FileNotFoundError: Could not find config file $RLBOTPACKROOT\RLBotPack\Kamael_family\peter.cfg! How can I fix this?

**Comment by Lautaro-cloud** [comment]
> Hello I am attempting to playthrough the story mode on RLBOT and when attempting to play the match titled "How does the car turn so fast" it fails and gives an error in the console reading FileNotFoundError: Could not find config file $RLBOTPACKROOT\RLBotPack\Kamael_family\peter.cfg! How can I fix this?

I have the same issue

**Comment by NicEastvillage** [comment]
Will be fixed in https://github.com/RLBot/RLBotGUI/pull/209
