### ISSUE TITLE
installation: ModuleNotFoundError: No module named 'rlbot_gui

### ISSUE THREAD

**Issue by playingbots** [RLBot/RLBot#615]
<img width="824" alt="error rlbot" src="https://github.com/RLBot/RLBot/assets/134103454/e271b948-cedc-4e7c-adb3-faf09410ce38">

I've been trying to download rlbot of days now and this keeps coming up I've been uninstalling it and repairing it and still not working, if someone knows how to fix it can you please tell me!

**Comment by playingbots** [comment]
please someone help me

**Comment by Ahmed7527** [comment]
have you downloaded rl bot pypi in first opeinng?

**Comment by playingbots** [comment]
yes it comes up as that at first

**Comment by playingbots** [comment]
<img width="945" alt="image" src="https://github.com/RLBot/RLBot/assets/134103454/e99f119e-0b70-4db1-9c38-c2990e050757">



i reeset my laptop and it came up as this this time do you still know how to fix this

**Comment by Ahmed7527** [comment]
your rl pypi is damgged.
try:
1. use vpn
2. reinstall rl bot
3. reinstall python
4. reinstall some drivers(visual c++ latset version(32x with 64x), direct x, net framework 4.0 and new, other)
5. if problem not solved contact with RL Bot

**Comment by Ahmed7527** [comment]
and reinstall rl bot after updating drivers
