### ISSUE TITLE
RLBotGUI not launching

### ISSUE THREAD

**Issue by KartToonOFF** [RLBot/RLBot#617]
When launched, i need to install python but i already have it and then it say that package upgrades are skipped and the file cannot be found.

![Capture d’écran 2023-06-01 110302](https://github.com/RLBot/RLBot/assets/95185459/dd88be11-bf6d-4a18-94ca-b5687918c0a8)

**Comment by NicEastvillage** [comment]
RLBotGUI installs its own Python environment to avoid messing with your existing Python.

As the console says, it failed to connect to pypi, which is required the first time RLBotGUI is run. Either try again later or reinstall.

If a file is missing, then a reinstall is required. The file may have been removed by your anti-virus. So try reading this first: https://github.com/RLBot/RLBot/wiki/Antivirus-Notes
