### ISSUE TITLE
Fix Python installer overwriting previous Python install

### ISSUE THREAD

**Issue by ddthj** [RLBot/RLBot#623]

**Comment by VirxEC** [comment]
The best solution for this is to unzip Python into RLBot like the [alternative installer](https://github.com/RLBot/RLBotGUI/tree/master/alternative-install) does. The problem is that there's no real, universal, and reliable way of unzipping anything on Windows machines using Windows CMD/Powershell.

**Comment by VirxEC** [comment]
We could bundle [`unzip.exe`](https://gnuwin32.sourceforge.net/packages/unzip.htm) which is only 165kb and use that to unzip the bundled `python-3.7.9-custom-amd64.zip` (same as the one currently in the alt installer)
