### ISSUE TITLE
Relocate wikis to searchable site

### ISSUE THREAD

**Issue by ddthj** [RLBot/RLBot#624]
Github Wikis are not accessible to search engines. We need a readthedocs or similar page on rlbot.org to house the wiki.

Question: Should language-specific wiki details stay on github? Or should everything be in one place? (I think the more we can consolidate information the better)

**Comment by TheBlocks** [comment]
I'm a fan of consolidating everything into one wiki. This makes the most sense for finding things easily.

Also a fan of using Read the Docs. It's a pretty popular platform so a lot of botmakers will probably be familiar with it already.

If we're not using Read the Docs, we could take a look at RLGym for inspiration: https://rlgym.org/

**Comment by TheBlocks** [comment]
After Contributor Meeting 2, we've decided on using MkDocs (https://github.com/mkdocs/mkdocs) for our documentation. We plan to host the docs using GitHub Pages.

We will have one repository as the main wiki (called RLBot/wiki). This will have tutorials and general knowledge about RLBot.

Language managers repos might have generated docs for API references. The main wiki can link to these auto generated docs.

**Comment by swz-git** [comment]
I moved all of the RLBot/RLBot wiki pages to mkdocs in this repo https://github.com/swz-git/rlbot-wiki

It's deployed with github pages here http://rlbot-docs.swz.works/

Any opinions?

**Comment by VirxEC** [comment]
Not bad! We would definitely move it into something like `wiki.rlbot.org` but I like the style overall, at the very least it's a good start.

**Comment by swz-git** [comment]
Yeah, I just deployed to to my site to show what it looks like. And I didnt really want to just push to RLBot/wiki.

**Comment by swz-git** [comment]
https://wiki.rlbot.org
