### ISSUE TITLE
Make FlatBuffers folder a submodule

### ISSUE THREAD

**Issue by TangilJ** [RLBot/RLBot#629]
All bot managers need to generate FlatBuffers models. Currently flatc.exe and the schema are stored in the main RLBot repo: https://github.com/RLBot/RLBot/tree/c2f7c9a07911691b112b5338008e2ec932e7aee0/src/main/flatbuffers. To prepare the dev environment, setup.bat is run so that the models are generated for each language.

We plan to move bot managers out of the main repository, so keeping everything FlatBuffers related in the main repo will not work. This is why we plan to make this a submodule and then add the submodule to the bot manager repos.

**Comment by TheBlocks** [comment]
A new repository with the flatbuffers schema has been created: https://github.com/RLBot/flatbuffers-schema

The C# bot manager uses this repo as a submodule: https://github.com/RLBot/csharp-manager/blob/3aaef5415aa132c831b28bcf9d3d97505e7c298b/.gitmodules

I will close this issue when [RLBot/RLBot](https://github.com/RLBot/RLBot) uses this submodule, as well as the Java and JavaScript bot manager repos.
