### ISSUE TITLE
Clarification Needed on GameTickPacket Handling in Python

### ISSUE THREAD

**Issue by MarlBurroW** [RLBot/RLBot#644]
I've been reviewing the source code and I can't find where the GameTickPacket FlatBuffer is converted into a Structure in the Python part. This leads me to believe that the GameTickPacket is not transmitted through the socket but instead retrieved by the Python script through a DLL function call via the Windows API. Am I correct in this understanding?

**Comment by VirxEC** [comment]
Yes and no - the DLL function you reference just reads from its own socket and converts it into something that Python can read for you. Other languages don't go through a DLL, as Python's way of doing things is legacy. The inconsistency has been addressed in the planning of RLBot v5.

The code in the DLL that does this can be found here: https://github.com/RLBot/RLBot/blob/master/src/main/cpp/RLBotInterface/src/RLBotInterface/GameFunctions/GamePacket.cpp
But there are better, cleaner implementations of this. What is your goal? Are you trying to implement the RLBot spec from scratch for a new language?

Also feel free to join the discord linked on our website (rlbot.org) if you want to chat about this or anything else with the rest of the RLBot community.

**Comment by MarlBurroW** [comment]
Thank you for your response,
I am in the process of creating a bot with the RLBot API, and I personally find RLBot to be quite an impressive technical achievement, so I have been thoroughly examining the code out of curiosity, to see how the machinery works.
