### ISSUE TITLE
rlbot.agents.base_agent error

### ISSUE THREAD

**Issue by gmoris38** [RLBot/RLBot#645]
When I run the code using Visual Studio Code, it says "ModuleNotFoundError: No module named 'rlbot'  "
Anyone else experiencing this issue?

**Comment by NicEastvillage** [comment]
Your python installation/virtual environment does not have the rlbot package. Either install it using `pip install rlbot` or set up your VS Code to use the RLBot GUI's python installation found in `%localappdata%\rlbotguix\python311`.
