### ISSUE TITLE
Binary?

### ISSUE THREAD

**Issue by DiadanKai** [RLBot/RLBot#650]
![Screenshot 2024-06-06 002353](https://github.com/RLBot/RLBot/assets/171881656/e0cfe364-8aac-4217-ad61-338c77e42b47)

**Comment by NicEastvillage** [comment]
Your anti-virus software has probably deleted one or more of the RLBot files (we are not registered software developers, but the code is open source so do not worry). See https://github.com/RLBot/RLBot/wiki/Antivirus-Notes for fixes.
