### ISSUE TITLE
No running event loop(Error)

### ISSUE THREAD

**Issue by bakboi124** [RLBot/RLBot#654]
So when i open up RLBot and try to start a match of any sort it gives an error which is "no running event loop" also it give like a little pop up which is "Error starting match: no running event loop See console for more details.". I tried reseting  rl i even closed bakkes mod  and it still didn't work .After that i tried  to reset RLBot app multiple times but to no avail nothing happend.

**Comment by robwetz** [comment]
same here.  just started recently.

**Comment by robwetz** [comment]
`RLBot.exe Connected successfully to port 23233 !
RLBot.exe listening for bot connections...
RLBot.exe has begun listening for local socket clients on port 23234.
20204 - C:\Users\r-xbo\AppData\Local\RLBotGUIX\Python311\python.exe DLL client connected from local port 55005, pid is 20204
RLBot.exe accepted new bot connection from 55005
20204 - C:\Users\r-xbo\AppData\Local\RLBotGUIX\Python311\python.exe Sending ready message...
2024-11-09 10:54:32,000 INFO:rlbot[   game_interface.py:277 - wait_until_ready_to_communicate() ] DLL is ready for comms!
2024-11-09 10:54:32,200 INFO:rlbot[   game_interface.py:264 -    wait_until_loaded() ] DLL is initialized!
2024-11-09 10:54:32,200 INFO:rlbot[   game_interface.py:338 -       load_interface() ] About to call StartTcp
20204 - C:\Users\r-xbo\AppData\Local\RLBotGUIX\Python311\python.exe DLL client connected from local port 55011, pid is 20204
RLBot.exe accepted new bot connection from 55011
20204 - C:\Users\r-xbo\AppData\Local\RLBotGUIX\Python311\python.exe Sending ready message...
2024-11-09 10:54:32,200 INFO:rlbot[   game_interface.py:277 - wait_until_ready_to_communicate() ] DLL is ready for comms!
no running event loop`

**Comment by herkedavid** [comment]
anybody know how to fix it?

**Comment by Rahail22** [comment]
Having the same issue. It was working yesterday when I booted RLBot. However today keep getting the no running event loop issue.

**Comment by Kaiyotech** [comment]
There's an issue with a Python package that updated today. This fix comes from swz until he can push a fix. 

temporary fix until swz can update guilauncher:
to run rlbot, paste this into the Run menu (`Win + R` to open)
`cmd /c "%localappdata%\rlbotguix\python311\python.exe -m uv pip install websockets==12 && %localappdata%\rlbotguix\rlbotguilauncher.exe --offline"`

**Comment by swz-git** [comment]
This issue is now [fixed](https://github.com/swz-git/guilauncher/releases/tag/v0.8.0) and the temporary fix is no longer needed. Restart your RLBot and it will update automatically.
