### ISSUE TITLE
Error: unexpected keyward argument 'callback'

### ISSUE THREAD

**Issue by Scrappy996** [RLBot/RLBot#655]
![17321539568768580872371828844953](https://github.com/user-attachments/assets/7f5d3b10-87ac-4b51-8807-616feecdd824)

**Comment by Scrappy996** [comment]
RL Launcher will not open

**Comment by Sean-Carrick** [comment]
Same here, exact same error message. I use RLbot a few times a week and this just started today!

**Comment by Rahail22** [comment]
Hi, I have the same issue; I assume it's because of an update. I tried using the offline version, but it did not work. I'm not sure if there is a workaround yet or if we have to wait for an update.

**Comment by swz-git** [comment]
Duplicate of https://github.com/RLBot/RLBotGUI/issues/233
