### ISSUE TITLE
LAN with RLBOT don't start

### ISSUE THREAD

**Issue by Somroti** [RLBot/RLBot#656]
When i start a match in lan i have an error : Console commands were used whitch are disallowed in netplay.

**Comment by NicEastvillage** [comment]
Are you using RocketPlugin like in [this guide](https://wiki.rlbot.org/miscellaneous/lan-setup/)?

**Comment by Somroti** [comment]
> Are you using RocketPlugin like in [this guide](https://wiki.rlbot.org/miscellaneous/lan-setup/)?

Im dumb i just activate a script (Quandtum League) but thanks
