### ISSUE TITLE
Fix jitter in 3d points centered around moving game objects

### ISSUE THREAD

**Issue by dtracers** [RLBot/RLBot#86]
Option:
We send down 2 3d anchors 
One for start and end vectors
then we populate it with a list of good known points:

- car 1-10
- ball
- center of both goals

Then in the core we will natively update the points based on the anchor choosen

**Comment by ddthj** [comment]
Could not reproduce on rlbot version 1.43.0, nor have I heard of anyone complaining about any jitter in over a year
